### ISSUE TITLE
slurmr R package

### ISSUE THREAD

**Issue by MansMeg** [stas-g/slurmR#1]
Hi!

I just saw this repository. Maybe we should work together. Ive done a simple R package for this here:
https://github.com/MansMeg/slurmr

**Comment by stas-g** [comment]
hi Magnus,

thank you for your message. i had a look at your repo and yes yours and
mine essentially do the same thing it seems. except mine works from the
linux command line.
what sort of collaboration do you have in mind?

best regards,
stasia

2017-03-07 8:08 GMT+00:00 Måns Magnusson <notifications@github.com>:

**Comment by MansMeg** [comment]
Hi!

None specific, just maybe join forces and try to put all functionality into one package maybe.

Skickat från min iPhone

**Comment by stas-g** [comment]
hi Mans,

yes, why not -- i think it's a good idea. 
drop me a message on my personal e-mail: n "dot" f "dot" grinberg "at" gmail "dot" com

best,
stasia
